EITParcelDelivery/Models/City.cs
namespace EITParcelDelivery.Models
{
    public class City
    {
        public int Id { get; set; }

        public string name { get; set; }

        public bool Available { get; set; }
    }
}

EITParcelDelivery/Models/LoginViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace EITParcelDelivery.Models
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

EITParcelDelivery/Models/SendParcelViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace EITParcelDelivery.Models
{
    public class SendParcelViewModel
    {
        [Required]
        [Range(0, 100)]
        [DisplayName("Weight (in kg)")]
        public int Weight { get; set; }

        [Required]
        public City Source { get; set; }

        [Required]
        public City Destination { get; set; }

        [Required]
        public ParcelType Type { get; set; }

        public List<City> Cities { get; set; }

        public List<ParcelType> ParcelTypes { get; set; }

        public IEnumerable<string> getCityNames()
        {
            return Cities.Where(c => c.Available).Select(c => c.Name);
        }

        public IEnumerable<string> getParcelTypes()
        {
            return ParcelTypes.Select(pt => pt.Type);
        }
    }
}

EITParcelDelivery/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EITParcelDelivery.Database.Repositories;

namespace EITParcelDelivery.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login(string username, string password)
        {
            var userRepo = new UserRepository();
            var user = userRepo.get(username, password);
            if (user != null)
            {
                return Json(user.Id, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(0, JsonRequestBehavior.AllowGet);
            }
            
        }
    }
}

EITParcelDelivery/Controllers/SendParcelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EITParcelDelivery.Database.Repositories;
using EITParcelDelivery.Models;
using EITParcelDelivery.Repositories;

namespace EITParcelDelivery.Controllers
{
    public class SendParcelController : Controller
    {
        // GET: SendParcel
        public ActionResult Index()
        {
            var vm = new SendParcelViewModel();
            var cr = new CitiesRepository();
            var ptr = new ParcelTypesRepository();
            vm.Cities = cr.getAll();
            vm.ParcelTypes = ptr.getAll();
            return View(vm);
        }
    }
}

EITParcelDelivery/Controllers/apiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace EITParcelDelivery.Controllers
{
    public class apiController : Controller
    {
        public JsonResult parcelinformation(string source, string destination, int type, string token)
        {
            var data = new
            {
                available = true,
                price = 100,
                time = 10
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }

    }
}

EITParcelDelivery/Views/Login/Index.cshtml
@using EITParcelDelivery.Models
@model LoginViewModel



@{
    Layout = "~/Views/Shared/IndexLayout.cshtml";
    ViewBag.Title = "Log into dashboard";
}

<div class="row">
    <div class="col-md-4 col-md-offset-1">
        <h2>Track parcel</h2>
        <div class="tracking-container">
            <br /><br /><br /><br />
            <div class="form-group">
                <input type="text" class="form-control" id="trackingNumber" placeholder="Enter tracking number..">
            </div>
            <button id="trackingButton" type="submit" class="btn btn-primary btn-lg">Search</button>
        </div>
    </div>
    <div class="col-md-4 col-md-offset-2">
            <h2>Log into dashboard</h2>
            <div class="login-container">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                    <div class="form-group">
                        @Html.LabelFor(x => x.Username)
                        @Html.TextBoxFor(x => x.Username, new {@class = "form-control", placeholder = "Username", id = "username"})
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.Password)
                        @Html.PasswordFor(x => x.Password, new {@class = "form-control", placeholder = "Password", id = "password"})
                    </div>
                    <button id="loginButton" type="submit" class="btn btn-primary btn-lg">Login</button>
                }
            </div>
    </div>
</div>






@section scripts {
    <script type="text/javascript">
        $("#loginButton").click(function(event) {
            event.preventDefault();
            var user = $("#username").val();
            var pass = $("#password").val();
            $.ajax({
                url: "@Url.Action("Login", "Login")",
                type: "GET",
                data: { username: user, password: pass },
                success: function(id) {
                    if (id === 0) {
                        alert("Error");
                    } else {
                        var url = '@Url.Action("Index", "SendParcel", new { id = "__id__" })';
                        window.location.href = url.replace('__id__', id);
                    }
                },
                error: function(error) {
                    alert(result);
                }
            });
        })
    </script>
}

EITParcelDelivery/Views/SendParcel/Index.cshtml
@using EITParcelDelivery.Models
@model SendParcelViewModel

@{
    Layout = "~/Views/Shared/PageLayout.cshtml";
    ViewBag.Title = "Send parcel";
}

<div>
    <h1>@ViewBag.Title</h1>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        <div class="form-group">
            @Html.LabelFor(x => x.Weight)
            @Html.TextBoxFor(x => x.Weight, new { @class = "form-control", placeholder = "Weight", id = "weight", @type = "number" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Source)
            @Html.DropDownListFor(x => x.Source, new SelectList(@Model.getCityNames()), new { @class = "form-control", id = "source" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Destination)
            @Html.DropDownListFor(x => x.Destination, new SelectList(@Model.getCityNames()), new { @class = "form-control", id = "destination" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Type)
            @Html.DropDownListFor(x => x.Type, new SelectList(@Model.getParcelTypes()), new { @class = "form-control", id = "type" })
        </div>

        <button id="sendButton" type="submit" class="btn btn-primary btn-lg">Find routes</button>
    }
</div>

EITParcelDelivery/Views/Shared/IndexLayout.cshtml
@{
    ViewBag.Company = "East India Trading Co.";
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @ViewBag.Company</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="index-page">
    <div class="navbar navbar-fixed-top logo-header">
        <div class="container logo-container">
            <img src="@Url.Content("~/Content/Images/eit-logo.png")" width="128px" alt="East India Trading Co." />
        </div>
    </div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year &emsp; @ViewBag.Company</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

EITParcelDelivery/Views/Shared/PageLayout.cshtml
@{
    ViewBag.Company = "East India Trading Co.";
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @ViewBag.Company</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="content-page">
    <div class="navbar navbar-fixed-top logo-header">
        <div class="container logo-container">
            <img src="@Url.Content("~/Content/Images/eit-logo.png")" width="128px" alt="East India Trading Co." />
        </div>
    </div>
    <div class="container body-content ">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year &emsp; @ViewBag.Company</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

EITParcelDelivery/Views/Shared/_Layout.cshtml
@{
    ViewBag.Company = "East India Trading Co.";
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @ViewBag.Company</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="content-page">
<div class="navbar navbar-fixed-top logo-header">
    <div class="container logo-container">
        <img src="@Url.Content("~/Content/Images/eit-logo.png")" width="128px" alt="East India Trading Co." />
    </div>
</div>
<div class="container body-content ">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year &emsp; @ViewBag.Company</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>